#!/usr/bin/env node

var net          = require( 'net' ),
    repl         = require( 'repl' ),
    version      = '0.0.1',
    Config       = require( './config/ocap.js' ).Config,
    Library      = require( './lib/ocap/main.js' ).OCAP,
    DEBUG        = false,
    Env          = require( './lib/env.js' ).Env,
    Prompt       = require( './lib/prompt.js' ).Prompt,
    Shell        = require( './lib/shell.js' ).Shell,
    Util         = require( './lib/util.js' ).Util;

//
// load function library
//
var library = new Library( Config.agentString + version );

//
// ready command-line prompt
//
var prompt = new Prompt( {
  default       : function () { return Config.promptPrefix; },
  exitMsg       : Config.exitMsg,
  helpBlurb     : Config.helpBlurb,
  title         : Config.title,
  version       : version
} );

//
// have prompt return after commands complete
//
var postCommandHandler = function ( promptContent, msg ) {
  if ( msg ) {
    console.log( msg );
  }
  if ( promptContent )  {
    prompt.content = function () { return promptContent + '> '; };
  }
  prompt.show();
};

//
// supply function for booting system
//
var bootupHandler = function ( connectionId, connection ) {
  library.loginUser( connectionId, connection, postCommandHandler );
};

//
// boot shell
//
var env = new Env( version, bootupHandler, postCommandHandler );
library.isDebugging( env.context.debug ); 
var shell = new Shell( env, prompt, library );

//
// program shell commands
//
shell.prompt.handleCommand = function ( command ) {

  //
  // [integer] (connection alias)
  //
  if ( /^\s*\d+\s*$/.test( command ) ) {
    var connections = shell.env.connections;
    var found = false;
    for ( var c in connections ) {
      var connection = connections[ c ];
      if (connection.id == command) {
        found = true; 
        if ( connection.password )
          delete connection.password;
        shell.login(c, Config.sessionTimeout);
        return;
      }
    }
    if ( !found ) {
      console.log( Config.notFoundMsg );
      shell.prompt.show();
    }
  }

  //
  // <user>@<instance> (connect)
  //
  else if ( /^\s*[A-Za-z0-9\-_]+\@.+[\@A-Za-z0-9\-_]*\s*$/.test( command ) ) {
    shell.login( command, Config.sessionTimeout );
    return;
  }

  //
  // baskets - b 
  //
  else if ( /^\s*(b|baskets)\s+\d+\s*\d*\s*$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    command = command.split(/\s+/);
    var connectionId = shell.env.connectionString();
    var eventId      = command[1] && command[1].trim();
    var id           = command[2] && command[2].trim();
    if ( eventId && id ) {
      try {
        if ( shell.env.connections[connectionId].events[eventId].baskets[id] ) {
          shell.log( shell.env.connections[connectionId].events[eventId].baskets[id] );
        }
        else {
          console.log( Config.notFoundMsg );
        }
      }
      catch ( err ) {
        try {
          if ( shell.env.connections[connectionId].events[eventId].event_participations[id] ) {
            shell.log( shell.env.connections[connectionId].events[eventId].event_participations[id] );
          }
          else {
            console.log( Config.notFoundMsg );
          }
        }
        catch ( err ) {
          console.log( Config.notFoundMsg );
        }
      }
    }
    else if ( eventId ) {
      try {
        if ( shell.env.connections[connectionId].events[eventId].baskets ) {
          for ( b in shell.env.connections[connectionId].events[eventId].baskets ) {
            shell.log( shell.env.connections[connectionId].events[eventId].baskets[b] );
          }
        }
        else {
          if ( shell.env.connections[connectionId].events[eventId].event_participations ) {
            for ( e in shell.env.connections[connectionId].events[eventId].event_participations ) {
              shell.log( shell.env.connections[connectionId].events[eventId].event_participations[e] );
            }
          }
        }
      }
      catch ( err ) {
        console.log( Config.notFoundMsg );
      }
    }
  }

  //
  // connections - c
  //
  else if ( /^\s*(c|connections)[ \@a-zA-Z0-9\-_]*$/.test( command ) ) {
 
    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    var connections  = shell.env.connections;
    for ( var c in connections ) {
      connections[c] = Util.sanitizeConnection( connections[c] );
    }
    var found     = false;
    if (  /^\s*(c|connections)\s+[\@a-zA-Z0-9\-_]+$/.test( command ) ) {
      var tokens = command.split(/\s+/);
      var connectionId = tokens[1].trim();
      if ( /^\d+$/.test( connectionId ) ) {
        for ( var c in connections ) {
          if ( connections[c].id == connectionId ) {
            found = true;
            shell.log( shell.env.connections[c] );
            break;
          }
        }
      }
      else {
        shell.log( connections[connectionId] );
        found = true;
      }
      if ( !found ) {
        console.log( Config.notFoundMsg );
      }
    }
    else if ( /^\s*(c|connections)\s*$/.test( command) ) {
      found = true;
      shell.log( shell.env.listConnections() );
    }
    if ( !found ) {
      console.log( Config.notFoundMsg );
    }
    shell.prompt.show();
    return;
  }

  //
  // delete connection - d
  //
  else if ( /^\s*(d|delete)\s+.+$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    command = command.split(/\s+/);

    var connectionId = command[1].trim();

    var found = false;

    if ( /^\d+$/.test( connectionId ) ) {
      var connections = shell.env.connections;
      for ( var c in connections ) {
        if (connections[c].id == connectionId) {
          found = true;
          delete shell.env.connections[c];
          if ( c == shell.env.connectionString() ) {
            shell.prompt.content = function () { return Config.promptPrefix };
            shell.prompt.set() ;
          }
        }
      } 
    }
    else {
      if ( shell.env.connections[connectionId] ) {
        found = true;
        delete shell.env.connections[connectionId];
        if ( c == shell.env.connectionString() ) {
          shell.prompt.content = function () { return Config.promptPrefix };
          shell.prompt.set() ;
        }
      }
    }
    if ( !found ) {
      console.log( Config.notFoundMsg );
    }
    shell.prompt.show();
    return;
  }

  //
  // environment - e 
  //
  else if ( /^\s*(e|environment)[ a-zA-Z0-9\-_]*$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    var login = shell.env.connectionString();
    var connection = shell.env.connections[login];
    connection = Util.sanitizeConnection( connection );
    if ( connection && /^\s*(e|environment)\s+[a-zA-Z0-9\-_]+$/.test( command ) ) {
      var c = command.split( /\s+/ );
      var attribute = c[1];
      shell.log( connection[attribute] );
    }
    else if ( connection && /^\s*(e|environment)\s*$/.test( command ) ) {
      connection = connection || {};
      var suppressDetail      =  {};
      suppressDetail.events   =  [];
      suppressDetail.invoices =  0;
      for ( c in connection ) {
        if ( c == 'events' ) {
          for ( eid in connection['events'] ) {
            suppressDetail.events.push(eid);
          }
        }
        else if ( c == 'invoices_local' ) {
          var totalInvoices = Object.keys( connection.invoices_local ).length;
          suppressDetail.invoices = totalInvoices;
        }
        else if ( c == 'sessionCookie' ) {
          var cookie = connection.sessionCookie.split( ' ' )[0];
          cookie = cookie && ( cookie.substr( 0,4 ) + '...' + cookie.substr( -5,5 ) );
          suppressDetail.sessionCookie = cookie;
        }
        else {
          suppressDetail[c] = connection[c];
        }
      }
      shell.log( suppressDetail );
    }
    else {
      console.log( Config.notFoundMsg );
    }
  }

  //
  // LOCK - L
  //
  else if ( /^\s*(L|LOCK)\s+\d+\s+\d+\s+\d+\s+[012]\s*$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    command = command.split( /\s+/ );
    var connectionId = shell.env.connectionString();
    var connection   = shell.env.connections[connectionId];
    var eventId      = command[1] && command[1].trim();
    var supplierId   = command[2] && command[2].trim();
    var basketId     = command[3] && command[3].trim();
    var statusCode   = command[4] && command[4].trim();
    shell.commands.lockBasket( connectionId, connection, eventId, supplierId, basketId, statusCode );
    shell.prompt.show();
    return;
  }

  //
  // help - h
  //
  else if ( /^\s*(h|help)\s*$/.test( command ) ) {
    Config.helpMsg( prompt );
    return;
  }

  //
  // invoices - i 
  //
  else if ( /^\s*(i|invoices)[ =<>a-zA-Z0-9\-\._]*$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    // has query
    if ( /^\s*(i|invoices)\s+[ =<>a-zA-Z0-9\-\._]+$/.test( command ) ) {
      var tokens = command.split( /\s+/ );

      if ( /^\s*(i|invoices)\s+(p|print)\s*$/.test( command ) ) {
        console.log( Config.invPrintMsg );
        var invoices = shell.env.connections[shell.env.connectionString()].invoices_local;
     
        var header = 'pollenware_invoice_id,';
        for ( var c in Config.invColumns ) {
          header = header + Config.invColumns[c] + ',';
        }
        shell.log( header.replace( /,$/, '' ) );
        var row = '';
        for ( var i in invoices ) {
          row = i + ',';
          for ( var c in Config.invColumns ) {
            row = row + invoices[i][Config.invColumns[c]] + ',';
          }
          shell.log( row.replace( /,$/, '' ) );
        }
      }
      else if ( /^\s*(i|invoices)\s+(c|clear)\s*$/.test( command ) ) {
        console.log( Config.invClearMsg );
        shell.env.connections[shell.env.connectionString()].invoices_local = {};
        delete shell.env.connections[shell.env.connectionString()].invoicePlaceholder;
      }
      else {
        tokens.shift();
        var query = tokens.join( ' ' );
        shell.commands.getInvoices( shell.env.connectionString(), query );
      }
    }

    // no query
    else if ( /^\s*(i|invoices)\s*$/.test( command ) ) {
      shell.commands.getInvoices( shell.env.connectionString() );
    }

    else {
      console.log( Config.notFoundMsg );
    }
  }

  //
  // javascript -j 
  //
  else if ( /^\s*(j|javascript)\s+.+$/.test( command ) ) {
    var tokens = command.split( /\s+/ );
    tokens.shift();
    var code = tokens.join( ' ' );
    try { shell.log( eval ( code ) ) ; } 
    catch ( err ) {
      console.log( err );
    }
  }

  //
  // log - l
  //
  else if ( /^\s*(l|log)\s*([c|w]|(clear|write))*$/.test( command ) ) {
    var tokens = command.split( /\s+/ );
    var instruction = tokens[1];
    var logText = JSON.stringify( shell.logData, null, 2 ) + ',';
    if ( instruction == 'c' || instruction == 'clear' ) {
      shell.logData = [];
      console.log( Config.logClearMsg );
    }
    else if ( instruction == 'w' || instruction == 'write' ) {
      var logFile = Config.logFile || ( process.argv[1].split( '/' ).pop() + '.log' );
      console.log( Config.logWriteMsg + ' ' + logFile + '...' );
      try {
        Util.appendFile( logFile,  logText );
      }
      catch ( err ) {
        console.log( err );
        self.prompt.show();
      }
    }
    else {
      console.log( logText );
    } 
  }

  //
  // offer - o
  //
  else if ( /^\s*(o|offer)\s+\d+\s+\d+\s+\d+\s*$/.test( command ) ) {

    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    command = command.split( /\s+/ );
    var connectionId = shell.env.connectionString();
    var connection   = shell.env.connections[connectionId];
    var eventId      = command[1] && command[1].trim();
    var basket       = command[2] && command[2].trim();
    var bps          = command[3] && command[3].trim();
    if ( !connection.events ) {
      console.log( Config.noEventsMsg );
      shell.prompt.show();
      return;
    }
    else if ( connection.user_type == Config.BUYER ) {
      console.log( Config.errorPrefix + ' - ' + Config.errorBuyerBid );
      shell.prompt.show();
      return;
    }
    else if ( !connection.events[eventId] ) {
      console.log( Config.notFoundMsg );
    }
    else if ( eventId && basket && bps ) {
      if ( connection.events[eventId] ) {
        var baskets = connection.events[eventId].event_participations;
        var found = false;
        var thisBasket = {};
        for ( b in baskets ) {
          if ( baskets[b].id == basket ) {
            found = true;
            thisBasket = baskets[b];
          }
        }
        if ( found ) {
          thisBasket.offer = bps;
          thisBasket.event = eventId;
          shell.commands.placeOffer( connectionId, thisBasket );
        }
        else {
          console.log( Config.notFoundMsg );
          shell.prompt.show();
        }
      }
      else if ( !connection.events[eventId] ) {
        console.log( Config.notFoundMsg );
      }
    }
    else {
      console.log( Config.notFoundMsg );
    }
  }

  //
  // quit - q
  //
  else if ( /^\s*(q|quit)\s*$/.test( command ) ) {
    console.log( Config.exitMsg );
    process.exit( 0 );
  }

  //
  // repl - r 
  //
  else if ( /^\s*(r|repl)\s*$/.test( command ) ) {
    var server = net.createServer( function ( socket ) {
      shell.replConnections += 1;
      repl.start( Config.replPrompt, socket, null, false ).context.shell = shell;
    });
    server.listen( Config.replPort || 5100 )
    server.on( 'error', function ( e ) {
      console.log(e);
      shell.prompt.show();
    });
    console.log( Config.replUseMsg + ' ' + Config.replAddress + ' ' + Config.replPort );
  }

  //
  // toggle - t
  //
  else if ( /^\s*(t|toggle)\s+[ \d\|ei]+$/i.test( command ) ) {
    if ( !shell.env.hasConnections() ) {
      shell.prompt.show();
      return;
    }

    var connectionId = shell.env.connectionString();
    var connection   = shell.env.connections[connectionId];

    if ( connection ) {

      for ( var e in connection.events ) {
        if (  connection.events[e].is_live || connection.events[e].is_buyer_live ) {
          console.log( Config.errorLiveEventMsg );
          shell.prompt.show();
          return;
        }
      }

      var invoiceIds = command.split( /\s+/ );
      invoiceIds.shift();
      var keep = [];
      var exclude = [];
      for ( var i in invoiceIds ) {
        var iId = invoiceIds[i];
        if (! /^[ieEI][\|\d]+$/.test( iId ) ) {
          console.log( Config.errorAmbiguous + ': ' + iId );
          continue;
        }
        else {
          if ( /^i/i.test( iId ) ) {
            iId = iId.replace(/[iI]/, '');
            keep.push( iId );
          }
          else if ( /^e/i.test( iId ) ) {
            iId = iId.replace(/[eE]/, '');
            exclude.push( iId );
          }
          else {
            console.log( Config.notFoundMsg );
            shell.prompt.show();
            return;
          }
        }
      }
      shell.commands.toggleInvoice( connectionId, keep, exclude );
    }
    else {
      console.log( Config.notFoundMsg );
      shell.prompt.show();
    }
  }

  //
  // unrecognized command
  //
  else {
    console.log( Config.notFoundMsg );
  }

  shell.prompt.show();

};
